import { buildDisplayName } from '../data/format.js';

const GENERIC_UNKNOWN_LABEL = 'Nom non renseigné';
const AUTO_PATTERN = /^AUTO_/u;

function normalizeString(value) {
  return typeof value === 'string' ? value.trim() : '';
}

function isAutoGeneratedCandidate({ record, personId, preferredCandidate }) {
  const candidate = normalizeString(preferredCandidate).toLowerCase();
  const recordName = normalizeString(record?.displayName).toLowerCase();
  const id = normalizeString(personId);
  if (!id || !AUTO_PATTERN.test(id)) {
    return false;
  }
  if (!candidate) {
    return true;
  }
  if (candidate === id.toLowerCase()) {
    return true;
  }
  if (candidate === `personne ${id}`.toLowerCase()) {
    return true;
  }
  if (recordName && recordName === candidate) {
    return true;
  }
  return false;
}

function formatAutoIndividualLabel(personId) {
  const id = normalizeString(personId);
  return {
    value: id ? `Individu générique (${id})` : 'Individu générique',
    isArtificial: true,
    reason: 'auto-individual'
  };
}

function getPartnerRecord(datum, findRecordById) {
  const spouseId = datum?.spouse?.data?.id || datum?.spouse?.data?.data?.id;
  if (!spouseId || typeof findRecordById !== 'function') {
    return { id: spouseId ?? '', record: null };
  }
  return { id: spouseId, record: findRecordById(spouseId) };
}

function getChildRecord(datum, findRecordById) {
  const payload = datum?.data || {};
  const childId = Array.isArray(payload?.rels?.children) && payload.rels.children.length > 0
    ? payload.rels.children[0]
    : null;
  if (!childId || typeof findRecordById !== 'function') {
    return { id: childId ?? '', record: null };
  }
  return { id: childId, record: findRecordById(childId) };
}

function buildPersonReference({ record, id }) {
  if (record) {
    const displayName = buildDisplayName(record);
    if (displayName) {
      return displayName;
    }
  }
  const fallbackId = normalizeString(id);
  return fallbackId ? `profil ${fallbackId}` : '';
}

function formatUnknownSpouseLabel({ gender, partnerRecord, partnerId }) {
  const partnerName = buildPersonReference({ record: partnerRecord, id: partnerId });
  const base = gender === 'F' ? 'Conjointe inconnue' : gender === 'M' ? 'Conjoint inconnu' : 'Conjoint(e) inconnu(e)';
  if (partnerName) {
    return `${base} de ${partnerName}`;
  }
  return base;
}

function formatUnknownParentLabel({ gender, childRecord, childId }) {
  const childName = buildPersonReference({ record: childRecord, id: childId });
  const base = gender === 'F' ? 'Mère inconnue' : gender === 'M' ? 'Père inconnu' : 'Parent inconnu';
  if (childName) {
    return `${base} d'un enfant ${childName}`;
  }
  return base;
}

function deriveGender(datum, record, details) {
  const genderValue = normalizeString(record?.gender || details?.gender || datum?.data?.data?.gender || datum?.data?.gender);
  if (!genderValue) {
    return 'U';
  }
  const normalized = genderValue.toUpperCase();
  if (normalized === 'M' || normalized === 'F') {
    return normalized;
  }
  return 'U';
}

function detectRelationKind(datum) {
  if (!datum) {
    return null;
  }
  const payload = datum?.data || {};
  if (datum?.spouse || (Array.isArray(payload?.rels?.spouses) && payload.rels.spouses.length > 0)) {
    return 'spouse';
  }
  if (Array.isArray(payload?.rels?.parents) && payload.rels.parents.length > 0) {
    return 'parent';
  }
  return null;
}

export function getFallbackCardLabel({
  datum,
  personId,
  record,
  details,
  findRecordById,
  preferredCandidate
} = {}) {
  const candidate = normalizeString(preferredCandidate);
  const id = normalizeString(personId || record?.id || datum?.data?.id || datum?.id || '');

  if (candidate && !isAutoGeneratedCandidate({ record, personId: id, preferredCandidate: candidate })) {
    return null;
  }

  if (isAutoGeneratedCandidate({ record, personId: id, preferredCandidate: candidate })) {
    return formatAutoIndividualLabel(id);
  }

  if (!record) {
    const relationKind = detectRelationKind(datum);
    const gender = deriveGender(datum, record, details);
    if (relationKind === 'spouse') {
      const { id: partnerId, record: partnerRecord } = getPartnerRecord(datum, findRecordById);
      return {
        value: formatUnknownSpouseLabel({ gender, partnerRecord, partnerId }),
        isArtificial: true,
        reason: 'missing-spouse'
      };
    }
    if (relationKind === 'parent') {
      const { id: childId, record: childRecord } = getChildRecord(datum, findRecordById);
      return {
        value: formatUnknownParentLabel({ gender, childRecord, childId }),
        isArtificial: true,
        reason: 'missing-parent'
      };
    }
    const fallbackSuffix = id ? ` (${id})` : '';
    return {
      value: `${GENERIC_UNKNOWN_LABEL}${fallbackSuffix}`,
      isArtificial: true,
      reason: 'missing-record'
    };
  }

  if (!candidate) {
    const fallbackSuffix = id ? ` (${id})` : '';
    return {
      value: `${GENERIC_UNKNOWN_LABEL}${fallbackSuffix}`,
      isArtificial: true,
      reason: 'empty-name'
    };
  }

  return null;
}
